config/routes.rb
Rails.application.routes.draw do
  resources :lessons
  devise_for :users
  root 'pages#index'
  get 'windows' => 'pages#windows'
  get 'trivias' => 'pages#trivias'
  get 'linux' => 'pages#linux'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
 mount_uploader :pdf, PdfUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(nickname) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    elsif conditions.has_key?(:nickname) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  include ApplicationHelper

  def configure_permitted_parameters
    added_attrs = [:nickname, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  expose :system_categories, -> { ["Windows", "Linux", "Others"] }
  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to windows_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lesson_params
    params.require(:lesson).permit(:subject, :descrpition, :system, :pdf)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def windows
    @lessons=Lesson.all
  end

  def linux
    @lessons=Lesson.all
  end

  def trivias
    @lessons=Lesson.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="container text-center" style="margin-top: 1.20em">
<p>Copyright © 2017 D.Dariasz.M . All Rights Reserved</p>
</footer>

app/views/layouts/_header.html.erb
<div class="container">

</div>

app/views/layouts/_login.html.erb
<ul class="nav navbar-nav navbar-right">
  <li>
    <a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
      <div class="modal-dialog">
        <div class="loginmodal-container">
          <h1>Login to Your Account</h1><br>
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name), method: :post) do |f| %>
              <%= f.input :login, required: false, autofocus: true, input_html: {class: "form-control"} %>
              <%= f.input :password, required: false %>
              <%= f.input :remember_me , as: :boolean if devise_mapping.rememberable? %>
              <%= f.button :submit, "Log in" %>
          <% end %>
        </div>
      </div>
    </div>
  </li>
</ul>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Cisco site</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/windows">Windows</a></li>
        <li><a href="/linux">Linux</a></li>
        <li><a href="/trivias">Trivias</a></li>
      </ul>
      <% !unless user_signed_in? %>
          <%= render 'layouts/login' %>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <div class="text-center" style="padding-top: 1.1em; color: white;">Logged
                as:&nbsp <%= current_user.nickname %></div>
            </li>
            <% if current_user.nickname == "admin" %>
                <li><%= link_to 'Add lesson', new_lesson_path %></li>
            <% end %>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CiscoSite</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/lessons/_form.html.erb
<%= simple_form_for(@lesson) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :subject, required: true %>
      <%= f.input :descrpition, as: :wysihtml5, wysihtml5: {'toolbar': {'color': true}} %>
      <%= f.input :system, collection: system_categories, label: "Choose system", required: true %>
      <%= f.input :pdf, label: "Add your attachament" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>
<div class="text-center">
<h1>Lessons</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Descrpition</th>
      <th>System</th>
      <th>Pdf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.subject %></td>
        <td><%= lesson.system %></td>
        <td><%= lesson.pdf %></td>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lesson', new_lesson_path %>
</div>

app/views/lessons/new.html.erb
      <h1>New Lesson</h1>

      <%= render 'form', lesson: @lesson %>

      <%= link_to 'Back', lessons_path, class:"btn btn-default", style: "display:block-inline" %>

app/views/lessons/show.html.erb
<p class="text-center" id="notice"><%= notice %></p>
<h1 class="text-center">
  <strong>Subject:</strong>
  <%= @lesson.subject %>
</h1>
<hr class="divider_line">
<h2>
  <h3 class="text-center"><b>Descrpition:</b></h3>
  <%= @lesson.descrpition.html_safe %>
</h2>


<% if signed_in? %>
    <p>
      <%= link_to @lesson.pdf_url, download: @lesson.subject do %>
          <button type="button" class="btn btn-default" aria-label="Left Align">
            <span class="glyphicon glyphicon-floppy-open" aria-hiden="true"></span>
          </button>
      <% end %>

    </p>
<% end %>
<div class="text-right">
  <%= link_to edit_lesson_path(@lesson) do %>
      <button type="button" class="btn btn-default" aria-label="Left Align">
        <span class="glyphicon glyphicon-cog" aria-hiden="true"></span>
      </button>
  <% end %>
</div>

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">Welcome. <br/><br/> This page is dedicated to everyone who has a web lessons in ZSEEIM.
      <br/> There are a lot of questions which will help you with your trouble. </h1>
    <h2 class="text-center">Choose wisely:</h2>
    <div class="col-lg-6">
      <br/>
      <%= link_to windows_path do %>
          <%= image_tag 'Xplogo.jpg', width: "100%" %>
      <% end %>
    </div>
    <div class="col-lg-6">
      <br/>
      <%= link_to linux_path do %>
          <%= image_tag 'Tux.jpg', width: "90%" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/linux.html.erb
<div class="container">
  <h2 class="text-center">Here. You can find all of questions associated with a Linux.</h2><br/>

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <input type="search" id="search" value="" class="form-control" placeholder="Search using Fuzzy searching">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table" id="table">
        <thead>
        <tr>
          <th class="col-lg-8">Subject</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @lessons.each do |lesson| %>
            <% if lesson.system == "Linux" %>
                <tr>
                  <td>
                    <%= link_to lesson do %>
                        <%= lesson.subject %>
                    <% end %>
                  </td>
                  <td></td>
                  <% if signed_in? %>
                      <td class="text-right">
                        <%= link_to lesson do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-arrow-right" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to lesson.pdf_url, download: lesson.subject do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-floppy-open" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to edit_lesson_path(lesson) do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-cog" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to lesson, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-remove" aria-hiden="true"></span>
                            </button>
                        <% end %>
                      </td>


                <% end %>
                </tr>

            <% end end %>
        </tbody>
      </table>
      <hr>
    </div>
  </div>


</div>

<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>

app/views/pages/trivias.html.erb
<div class="container">
  <h2 class="text-center">Here. You can find all of questions associated with a Trivias.</h2><br/>

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <input type="search" id="search" value="" class="form-control" placeholder="Search using Fuzzy searching">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table" id="table">
        <thead>
        <tr>
          <th class="col-lg-8">Subject</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @lessons.each do |lesson| %>
            <% if lesson.system == "Trivias" %>
                <tr>
                  <td>
                    <%= link_to lesson do %>
                        <%= lesson.subject %>
                    <% end %>
                  </td>
                  <td></td>
                  <% if signed_in? %>
                      <td class="text-right">
                        <%= link_to lesson do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-arrow-right" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to lesson.pdf_url, download: lesson.subject do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-floppy-open" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to edit_lesson_path(lesson) do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-cog" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to lesson, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-remove" aria-hiden="true"></span>
                            </button>
                        <% end %>
                      </td>


                <% end %>
                </tr>

            <% end end %>
        </tbody>
      </table>
      <hr>
    </div>
  </div>


</div>

<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>

app/views/pages/windows.html.erb
<div class="container">
  <h2 class="text-center">Here. You can find all of questions associated with a Windows.</h2><br/>

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <input type="search" id="search" value="" class="form-control" placeholder="Search using Fuzzy searching">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table" id="table">
        <thead>
        <tr>
          <th class="col-lg-8">Subject</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @lessons.each do |lesson| %>
            <% if lesson.system == "Windows" %>
                <tr>
                  <td>
                    <%= link_to lesson do %>
                        <%= lesson.subject %>
                    <% end %>
                  </td>
                  <td></td>
                  <% if signed_in? %>
                      <td class="text-right">
                        <%= link_to lesson do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-arrow-right" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to lesson.pdf_url, download: lesson.subject do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-floppy-open" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to edit_lesson_path(lesson) do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-cog" aria-hiden="true"></span>
                            </button>
                        <% end %>
                        <%= link_to lesson, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <button type="button" class="btn btn-default" aria-label="Left Align">
                              <span class="glyphicon glyphicon-remove" aria-hiden="true"></span>
                            </button>
                        <% end %>
                      </td>

                  <% end %>
                </tr>

            <% end end %>
        </tbody>
      </table>
      <hr>
    </div>
  </div>


</div>

<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>